[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = {version="2.0.114", features=["full", "extra-traits"]}
# TODO
